language: cpp

compiler:
  - clang

script:
  - make tests


notifications:
  email:
    recipients:
      - your_TAs_email@nyu.edu
    on_success: always
    on_failure: never

    recipients:
      - ksv244@nyu.edu
    on_success: always
    on_failure: always
